ansible_host: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  62653365666131666161313237333262363137343638313133656231666439616665633664306636
  3333366133623634333632323264613961643963303334660a366162623263336238386630323664
  62613766323266356366396461366630376361663433333439366436623139656637313134616235
  3131376335336463620a383762353462313966303064323261396465633932636566373062306362
  33326631336265363933373962323032366637343236306338363838663736343761

authorized_keys:
  - key: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMNxxAEcT71BAXlVhmi76gjI26BkXwjAgcLaPLIMI+i8 dmiller
    user: parallels
    state: present
  - key: ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBPUgzXYNTvTCcUHjzdXvy2LZA6YFZKrHrfsse3ipP2ldbhnmU/Io9I/lUligmdaCFktcxwgzZRYawWJI1IsUnZA= dmiller
    user: parallels
    state: present
  - key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQChNryHWkasg7O7YLfLSffWjrP+e6eAt5olYIPgBCeqBgPHYK3sJkAo/UHuJ1SQA22qMQlHI/2m2chASZ7tbbkaBEkWlBlbAQpwleuJE0WBN8hJd49dJToW9d6q6hNwq9bmnlA/VTkzsLAqpSEANnO28WMhHI+Upn924L4lC4tVJQmSUPm8ENgU5RVW9EcSkfIBPrIdFW0zqxPEFzZXlaOqxmbOvgS4qWirjHe4PXC1Z8DeYlK9DSTM/KGX0pz8Jgz0shKwxDpdn/j36KP1jlygwrWmnDXuWuMuU44HjMZzA3A9XKuHqiROrv1K0A4M1t5DN/UbWSNQBhQOWdica2Qaek2+dUQ5m5bgYw7sSTW5Oz/jvWU71NdFhmN9eXCJukiN7UwznecnOHf0O/Si5fFf6iJzLjHELi1JKzVLvADyZTlaxmZB82MmveB99eArOUquaeO4rOHugmOVosW/Gg4wj1j19gFy0E+yVuP01tg999YF2ST8l6Z81w2xBrZYKKw+tgQlm/WbxkzRxnumTx7JH/AddFTZvTADQB11DRySmrWBKC4QCGo8+8SdwitHt6WzDZAuOqYPK+mtMtGY3TKGazRRUvCKVTALamJWjbZcizQGj3PqfVr8+wB/+TzsUU9vJPPo9skZrYHwom/3Wu1TlAAaYd8hTriqGK7gzm1CNw== dmiller
    user: parallels
    state: present

additional_docker_users:
  - parallels

sudoers:
  - user: parallels
    passwordless: true

project_files:
  - src: "plaintext/{{ inventory_hostname }}/var/docker/"
    dest: /var/docker/

tailscale_args: --accept-routes

# Docker Swarm configuration
docker_swarm_network_interface: enp0s5
