- assert:
    that: nvidia_overclock_state in ('present', 'absent')

- name: check if coolbits are enabled
  command: grep -q Coolbits /etc/X11/xorg.conf
  changed_when: false
  failed_when: true
  register: xorg_coolbits

- when: xorg_coolbits.rc != 0
  block:
    - name: enable coolbits
      command: nvidia-xconfig --allow-empty-initial-configuration --enable-all-gpus --cool-bits=28 --separate-x-screens

    - name: reboot after enabling coolbits
      reboot:

- name: copy nvidia-overclock executable
  copy:
    src: nvidia-overclock
    dest: "{{ nvidia_overclock_exe }}"
    owner: root
    group: root
    mode: 0755
  when: nvidia_overclock_state == 'present'

- name: delete nvidia-overclock executable
  file:
    path: "{{ nvidia_overclock_exe }}"
    state: absent
  when: nvidia_overclock_state == 'absent'
