---
available_docker_images:
  sourcebot:
    repo: https://github.com/sourcebot-dev/sourcebot.git
    version: v4.10.3
    patches:
      - sourcebot/increase-heap.patch
      - sourcebot/vault-enable-demo-features.patch
    image_name: sourcebot
    image_tag: v4.10.3-patched