---
roles:
  - src: oefenweb.postfix
    name: galaxy/postfix
  - src: geerlingguy.docker
    name: galaxy/docker
  - src: nvidia.nvidia_driver
    name: galaxy/nvidia-drivers
  - src: artis3n.tailscale
    name: galaxy/tailscale
