nut_stats_state: "{{ 'present' if nut_stats_targets is truthy else 'absent' }}"
nut_stats_metric_name: ups
nut_stats_dir: /opt/nut-stats
nut_stats_script_path: "{{ nut_stats_dir }}/bin/nut-stats"
nut_stats_timeout_s: 5

# must set:
nut_stats_targets: []
