- assert:
    that: coin_stats_state in ('present', 'absent')

- when: coin_stats_state == 'present'
  block:
    - name: install python dependencies
      pip:
        virtualenv: "{{ coin_stats_virtualenv_path }}"
        name:
          - click
          - requests
        extra_args: --upgrade-strategy only-if-needed
        state: latest
      environment:
        SETUPTOOLS_USE_DISTUTILS: stdlib

    - name: create coin-stats script dir
      file:
        path: "{{ coin_stats_script_path|dirname }}"
        owner: root
        group: root
        mode: 0755
        state: directory

    - name: copy coin-stats script
      template:
        src: coin-stats.jinja2
        dest: "{{ coin_stats_script_path }}"
        owner: root
        group: root
        mode: 0755

- include_role:
    name: generic/telegraf/plugin
  vars:
      telegraf_plugin_conf_src: coin-stats.conf.jinja2
      telegraf_plugin_conf: coin-stats.conf
      telegraf_plugin_state: "{{ coin_stats_state }}"

- name: delete coin-stats dir
  file:
    path: "{{ coin_stats_dir }}"
    state: absent
  when: coin_stats_state == 'absent'
